language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO=django>=1.7,<1.8
  - DJANGO=django>=1.8,<1.9

install:
  - pip install django=$DJANGO
  - pip install -e .

script: ./example/manage.py test
